version: '3.8'

services:
  database:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ""
      POSTGRES_DB: currency_exchange
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      # Настройки для подключения к БД
      DB_URL: jdbc:postgresql://database:5432/currency_exchange
      DB_USER: postgres
      DB_PASSWORD: ""

volumes:
  postgres_data: